[profile.default]
src = "src"
out = "../frontend/src/Data/ABI"
libs = ["lib"]
broadcast = "../frontend/src/Data/BC"
solc = "/opt/homebrew/bin/solc"
offline = true

[rpc_endpoints]
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
