[profile.default]
src = "src"
out = "../frontend/src/Data/ABI"
libs = ["lib"]
broadcast = "../frontend/src/Data/BC"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
